### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by travisspencer** [yWorks/yGuard#116]
When I try to compile my code with Java 17 and obfuscate it, I get this error using version 3.0.0:

```
java.io.IOException: Incompatible version number for class file format: 61.0
        at com.yworks.yguard.obf.classfile.ClassFile.read(ClassFile.java:340)
        at com.yworks.yguard.obf.classfile.ClassFile.create(ClassFile.java:139)
        at com.yworks.yguard.obf.GuardDB.buildClassTree(GuardDB.java:727)
        at com.yworks.yguard.obf.GuardDB.retain(GuardDB.java:148)
        at com.yworks.yguard.ObfuscatorTask.execute(ObfuscatorTask.java:1063)
        at com.yworks.yguard.YGuardTask.execute(YGuardTask.java:118)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
```

To work around this, I add this to my build.gradle file:

```
compileKotlin {
    kotlinOptions {
        jvmTarget = "13"
    }
}
```

Is this because Java 17 isn't supported?

**Comment by Fohlen** [comment]
Indeed. See https://github.com/yWorks/yGuard/issues/108#issuecomment-959739823
