### ISSUE TITLE
Excluding clojure

### ISSUE THREAD

**Issue by Hosfad** [yWorks/yGuard#145]
Hello i am trying to obfuscate a jar , and im getting the following error :  

```
ant:rename] Invalid fully qualified name (a): clojure/inspector/proxy$javax/swing/table/AbstractTableModel$ff19274a
[ant:yguard] java.lang.IllegalArgumentException: Invalid fully qualified name (a): clojure/inspector/proxy$javax/swing/table/AbstractTableModel$ff19274a
[ant:yguard] 	at com.yworks.yguard.obf.ClassTree.getNameEnum(ClassTree.java:109)
[ant:yguard] 	at com.yworks.yguard.obf.ClassTree.addClassFile(ClassTree.java:300)
[ant:yguard] 	at com.yworks.yguard.obf.GuardDB.buildClassTree(GuardDB.java:760)
[ant:yguard] 	at com.yworks.yguard.obf.GuardDB.retain(GuardDB.java:150)
[ant:yguard] 	at com.yworks.yguard.ObfuscatorTask.execute(ObfuscatorTask.java:1224)
[ant:yguard] 	at com.yworks.yguard.YGuardTask.execute(YGuardTask.java:118)
[ant:yguard] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
[ant:yguard] 	at jdk.internal.reflect.GeneratedMethodAccessor508.invoke(Unknown Source)
[ant:yguard] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:yguard] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ant:yguard] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
[ant:yguard] 	at groovy.util.AntBuilder.performTask(AntBuilder.java:335)
[ant:yguard] 	at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:280)
[ant:yguard] 	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:90)
[ant:yguard] 	at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:160)
[ant:yguard] 	at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:215)
[ant:yguard] 	at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:117)
[ant:yguard] 	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:74)
[ant:yguard] 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
[ant:yguard] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
[ant:yguard] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[ant:yguard] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
[ant:yguard] 	at build_abf3bzoy45lms7hn5gc8bc8ym$_run_closure7$_closure22.doCall(C:\Users\home\OneDrive\Desktop\SideProjects\OsrsBot\build.gradle:126)
[ant:yguard] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ant:yguard] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ant:yguard] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:yguard] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ant:yguard] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
[ant:yguard] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
[ant:yguard] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
[ant:yguard] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
[ant:yguard] 	at groovy.lang.Closure.call(Closure.java:412)
[ant:yguard] 	at groovy.lang.Closure.call(Closure.java:428)
[ant:yguard] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.doExecute(AbstractTask.java:751)
[ant:yguard] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.lambda$execute$0(AbstractTask.java:738)
[ant:yguard] 	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:98)
[ant:yguard] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:738)
[ant:yguard] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:713)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:171)
[ant:yguard] 	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
[ant:yguard] 	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
[ant:yguard] 	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
[ant:yguard] 	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[ant:yguard] 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
[ant:yguard] 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
[ant:yguard] 	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
[ant:yguard] 	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
[ant:yguard] 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
[ant:yguard] 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
[ant:yguard] 	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
[ant:yguard] 	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
[ant:yguard] 	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
[ant:yguard] 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
[ant:yguard] 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
[ant:yguard] 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:61)
[ant:yguard] 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:42)
[ant:yguard] 	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
[ant:yguard] 	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
[ant:yguard] 	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:180)
[ant:yguard] 	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
[ant:yguard] 	at org.gradle.internal.Either$Right.fold(Either.java:175)
[ant:yguard] 	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
[ant:yguard] 	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
[ant:yguard] 	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
[ant:yguard] 	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
[ant:yguard] 	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
[ant:yguard] 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
[ant:yguard] 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
[ant:yguard] 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
[ant:yguard] 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
[ant:yguard] 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
[ant:yguard] 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
[ant:yguard] 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
[ant:yguard] 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
[ant:yguard] 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
[ant:yguard] 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:114)
[ant:yguard] 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
[ant:yguard] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
[ant:yguard] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:249)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
[ant:yguard] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:54)
[ant:yguard] 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
[ant:yguard] 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
[ant:yguard] 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
[ant:yguard] 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
[ant:yguard] 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
[ant:yguard] 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
[ant:yguard] 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
[ant:yguard] 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
[ant:yguard] 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
[ant:yguard] 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
[ant:yguard] 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
[ant:yguard] 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
[ant:yguard] 	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:144)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[ant:yguard] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[ant:yguard] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[ant:yguard] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
[ant:yguard] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
[ant:yguard] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
[ant:yguard] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
[ant:yguard] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
[ant:yguard] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
[ant:yguard] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
[ant:yguard] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
[ant:yguard] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
[ant:yguard] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[ant:yguard] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[ant:yguard] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[ant:yguard] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
```

Im thinking i need to exclude the clojure package , i tried doign the following : 

But it didnt work ?? thanks

```gradle

task obfuscate {
    dependsOn jar
    group 'yGuard'
    description 'Obfuscates the java archive.'

    doLast {
        def archivePath = jar.archiveFile.get().asFile.path
        def unobfJar = archivePath.replace(".jar", "_unobf.jar")

        ant.move(file: archivePath, tofile: unobfJar, verbose: true)

        ant.taskdef(
                name: 'yguard',
                classname: 'com.yworks.yguard.YGuardTask',
                classpath: configurations.yguard.asPath
        )

        ant.yguard {
            inoutpair(in: unobfJar, out: archivePath)
            rename(logfile: "${buildDir}/${rootProject.name}_renamelog.xml") {
                keep {

                    'package'(name: "org.clojure.**")

                }
            }
        }
    }
}

```

**Comment by thomasbehr** [comment]
Did you try to exclude `"clojure.**"` in addition to `"org.clojure.**"`? After all, the package name in the exception does not start with "org.clojure". That said, yGuard has never been tested with Clojure generated class files, it might very well be that it cannot handle those

**Comment by Fohlen** [comment]
This should *definitely* not work. Looking at the [Java interop section of Clojure], they rename e.g Array's on compilation. To do this, for Array type's, they use the `$` character. This will directly break yGuard, because we don't reserve `$` while obfuscating. It would be possible to adjust this, but then we would need dedicated support for Clojure. If this is something you are interested in, consider adding a pull request.

**Comment by Hosfad** [comment]
Hello, Thanks for the feedback, i was able to just completly get rid of clojure for now.
